In [1]:
from bs4 import BeautifulSoup
import pandas as pd
pd.set_option('display.max_rows', None)
import requests

In [2]:
url = "https://en.wikipedia.org/wiki/List_of_best-selling_video_games"
header = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url, headers=header)
soup = BeautifulSoup(response.content, "html.parser")

In [3]:
allTables = soup.find_all("table", {"class": "wikitable"})
gameTable = allTables[0]

#print(gameTable.prettify)
gameData = {}
for row in gameTable.find_all("tr")[1:]:
    idx = 1
    gameName = row.find("th").text.strip("\n")
    sales = row.find_all("td")[idx].text.strip("\n")
    idx += 3
    if sales.isalpha():
        sales = row.find_all("td")[0].text.strip("\n")
        idx-=1
    releaseYear = row.find_all("td")[idx].text.strip("\n")
    print(f"{gameName} sold {sales} in {releaseYear}")

Tetris sold 520 in 1988[c]
Minecraft sold 350 in 2011[d]
Grand Theft Auto V sold 230 in 2013
Red Dead Redemption 2 sold 85 in 2018
Wii Sports [b] sold 82.9 in 2006
Mario Kart 8 / Deluxe sold 79.54 in 2014
PUBG: Battlegrounds sold 75 in 2017
Terraria sold 70 in 2011
The Witcher 3: Wild Hunt sold 60 in 2015
Super Mario Bros.  sold 58 in 1985
Human: Fall Flat sold 55 in 2016
Overwatch sold 50 in 2016
The Sims sold The Sims in Maxis
Stardew Valley sold 50 in 2016
Animal Crossing: New Horizons sold 49.91 in 2020
Pokémon Red / Blue / Yellow sold 47.44 in 1996
Wii Fit / Plus  sold 43.8 in 2007
Call of Duty: Black Ops III sold 43 in 2015
Call of Duty: Modern Warfare sold 41 in 2019
Hogwarts Legacy sold 40 in 2023
Payday 2 sold 40 in 2013
Sonic the Hedgehog  sold Sonic the Hedgehog in Sonic Team
Super Smash Bros. Ultimate sold 37.76 in 2018
Mario Kart Wii  sold 37.38 in 2008
The Legend of Zelda: Breath of the Wild sold 35.54 in 2017
Cyberpunk 2077 sold 35 in 2020
Wii Sports Resort  sold 33.14 in 2009
New Super Mario Bros. sold 30.8 in 2006
Super Mario Odyssey sold 30.50 in 2017
New Super Mario Bros. Wii sold 30.32 in 2009
Pokémon Gold / Silver / Crystal sold 30.12 in 1999
Elden Ring sold 30 in 2022
Borderlands 2 sold 30 in 2012
Call of Duty: Black Ops Cold War sold Call of Duty in Treyarch / Raven Software
The Elder Scrolls V: Skyrim sold The Elder Scrolls in Bethesda Game Studios
It Takes Two sold 30 in 2021
Monster Hunter: World sold 29.1 in 2018
Duck Hunt  sold 28.3 in 1984
Pokémon Scarlet / Violet sold 28.28 in 2022
Wii Play  sold 28.02 in 2006
Black Myth: Wukong sold 28 in 2024
Grand Theft Auto: San Andreas sold 27.5 in 2004
Pokémon Sword / Shield sold 27.16 in 2019
The Last of Us / Remastered sold 26.6 in 2013
Call of Duty: Modern Warfare 3 sold 26.5 in 2011
Call of Duty: Black Ops sold 26.2 in 2010
Marvel's Spider-Man / Remastered sold 26.1 in 2018
Pokémon Sun / Moon / Ultra Sun / Ultra Moon sold 25.62 in 2016
Garry's Mod sold 25.56 in 2006
Pokémon Diamond / Pearl / Platinum sold 25.5 in 2006
Phasmophobia sold 25 in 2020[o]
Grand Theft Auto IV sold Grand Theft Auto in Rockstar North

In [4]:
url = "https://en.wikipedia.org/wiki/List_of_best-selling_books"
header = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)"}
response = requests.get(url, headers=header)
soup = BeautifulSoup(response.content, "html.parser")

In [5]:
allTables = soup.find_all("table", {"class": "wikitable"})
copies1M =  allTables[0]
bestBooks = []

for row in copies1M.find_all("tr")[1:]:
    title = row.find_all("td")[0].text.strip()
    author = row.find_all("td")[1].text.strip()
    year = row.find_all("td")[3].text.strip()
    sales = row.find_all("td")[4].text.strip().split("million")[0]
    genre = row.find_all("td")[5].text.strip()
    if not sales[0].isnumeric():
        sales = sales[1:]
    sales = int(sales)
    bestBooks.append({"Title": title, "Author": author, "Year": year, "Sales": sales, "Genre": genre})
    
print(bestBooks)

[{'Title': 'A Tale of Two Cities', 'Author': 'Charles Dickens', 'Year': '1859', 'Sales': 200, 'Genre': 'Historical fiction'}, {'Title': 'The Little Prince (Le Petit Prince)', 'Author': 'Antoine de Saint-Exupéry', 'Year': '1943', 'Sales': 200, 'Genre': 'Fantasy'}, {'Title': 'The Alchemist (O Alquimista)', 'Author': 'Paulo Coelho', 'Year': '1988', 'Sales': 150, 'Genre': 'Fantasy'}, {'Title': "Harry Potter and the Philosopher's Stone", 'Author': 'J. K. Rowling', 'Year': '1997', 'Sales': 120, 'Genre': 'Fantasy'}, {'Title': 'And Then There Were None', 'Author': 'Agatha Christie', 'Year': '1939', 'Sales': 100, 'Genre': 'Mystery'}, {'Title': 'Dream of the Red Chamber (紅樓夢)', 'Author': 'Cao Xueqin', 'Year': '1791', 'Sales': 100, 'Genre': 'Family saga'}, {'Title': 'The Hobbit', 'Author': 'J. R. R. Tolkien', 'Year': '1937', 'Sales': 100, 'Genre': "Fantasy, children's fiction"}, {'Title': "Alice's Adventures in Wonderland", 'Author': 'Lewis Carroll', 'Year': '1865', 'Sales': 100, 'Genre': 'Fantasy, absurdist fiction'}]

In [6]:
bestSellingBooks = pd.DataFrame(bestBooks)
bestSellingBooks

,Title,Author,Year,Sales,Genre
0,A Tale of Two Cities,Charles Dickens,1859,200,Historical fiction
1,The Little Prince (Le Petit Prince),Antoine de Saint-Exupéry,1943,200,Fantasy
2,The Alchemist (O Alquimista),Paulo Coelho,1988,150,Fantasy
3,Harry Potter and the Philosopher's Stone,J. K. Rowling,1997,120,Fantasy
4,And Then There Were None,Agatha Christie,1939,100,Mystery
5,Dream of the Red Chamber (紅樓夢),Cao Xueqin,1791,100,Family saga
6,The Hobbit,J. R. R. Tolkien,1937,100,"Fantasy, children's fiction"
7,Alice's Adventures in Wonderland,Lewis Carroll,1865,100,"Fantasy, absurdist fiction"

In [7]:
def addToDataFrame(tableNum):
    global bestSellingBooks
    copies1M =  allTables[tableNum]
    bestBooks = []

    for row in copies1M.find_all("tr")[1:]:
        title = row.find_all("td")[0].text.strip()
        author = row.find_all("td")[1].text.strip()
        year = row.find_all("td")[3].text.strip()
        sales = row.find_all("td")[4].text.strip().split("million")[0]
        try:
            genre = row.find_all("td")[5].text.strip()
        except:
            genre = "N/A"
        if not sales[0].isnumeric():
            sales = sales[1:]
        try:
            sales = float(sales)
        except:
            sales = sales
        
        bestBooks.append({"Title": title, "Author": author, "Year": year, "Sales": sales, "Genre": genre})

    temp = pd.DataFrame(bestBooks)
    bestSellingBooks = pd.concat([bestSellingBooks, temp], axis = 0, join = "outer", ignore_index=True)

In [8]:
for n in range(1, 3):
    addToDataFrame(n)

In [9]:
bestSellingBooks

,Title,Author,Year,Sales,Genre
0,A Tale of Two Cities,Charles Dickens,1859,200.0,Historical fiction
1,The Little Prince (Le Petit Prince),Antoine de Saint-Exupéry,1943,200.0,Fantasy
2,The Alchemist (O Alquimista),Paulo Coelho,1988,150.0,Fantasy
3,Harry Potter and the Philosopher's Stone,J. K. Rowling,1997,120.0,Fantasy
4,And Then There Were None,Agatha Christie,1939,100.0,Mystery
5,Dream of the Red Chamber (紅樓夢),Cao Xueqin,1791,100.0,Family saga
6,The Hobbit,J. R. R. Tolkien,1937,100.0,"Fantasy, children's fiction"
7,Alice's Adventures in Wonderland,Lewis Carroll,1865,100.0,"Fantasy, absurdist fiction"
8,She: A History of Adventure,H. Rider Haggard,1887,83.0,Adventure
9,The Da Vinci Code,Dan Brown,2003,80.0,Mystery thriller
10,Harry Potter and the Chamber of Secrets,J. K. Rowling,1998,77.0,Fantasy
11,The Catcher in the Rye,J. D. Salinger,1951,65.0,Coming-of-age
12,Harry Potter and the Prisoner of Azkaban,J. K. Rowling,1999,65.0,Fantasy
13,Harry Potter and the Goblet of Fire,J. K. Rowling,2000,65.0,Fantasy
14,Harry Potter and the Order of Phoenix,J. K. Rowling,2003,65.0,Fantasy
15,Harry Potter and the Half-Blood Prince,J. K. Rowling,2005,65.0,Fantasy
16,Harry Potter and the Deathly Hallows,J. K. Rowling,2007,65.0,Fantasy
17,Sophie's World (Sofies verden),Jostein Gaarder,1991,60.0,"Philosophical novel, Young adult"
18,The Bridges of Madison County,Robert James Waller,1992,60.0,Romance
19,One Hundred Years of Solitude (Cien años de so...,Gabriel García Márquez,1967,50.0,Magic realism
20,Lolita,Vladimir Nabokov,1955,50.0,Novel
21,Heidi,Johanna Spyri,1880,50.0,Children's fiction
22,The Common Sense Book of Baby and Child Care,Benjamin Spock,1946,50.0,Manual
23,Anne of Green Gables,Lucy Maud Montgomery,1908,50.0,Children's novel
24,Black Beauty,Anna Sewell,1877,50.0,Children's literature
25,The Name of the Rose (Il Nome della Rosa),Umberto Eco,1980,50.0,"Historical novel, mystery"
26,The Eagle Has Landed,Jack Higgins,1975,50.0,"War, thriller"
27,Watership Down,Richard Adams,1972,50.0,Children's fiction
28,The Hite Report,Shere Hite,1976,50.0,nonfiction
29,Charlotte's Web,E. B. White,1952,50.0,Children's fiction
30,The Ginger Man,J. P. Donleavy,1955,50.0,Novel
31,The Purpose Driven Life,Rick Warren,2002,50.0,Bible study
32,The Tale of Peter Rabbit,Beatrix Potter,1902,45.0,Children's literature
33,Jonathan Livingston Seagull,Richard Bach,1970,44.0,"Novella, self-help"
34,The Very Hungry Caterpillar,Eric Carle,1969,43.0,"Children's literature, picture book"
35,A Message to Garcia,Elbert Hubbard,1899,40.0,Essay/literature
36,To Kill a Mockingbird,Harper Lee,1960,40.0,"Southern Gothic, Bildungsroman"
37,Flowers in the Attic,V. C. Andrews,1979,40.0,"Gothic horror, family saga"
38,Cosmos,Carl Sagan,1980,40.0,"Popular science, anthropology, astrophysics, c..."
39,Angels & Demons,Dan Brown,2000,39.0,mystery-thriller
40,Alcoholics Anonymous,William Griffith Wilson,1939,37.0,Self-help
41,Kane and Abel,Jeffrey Archer,1979,37.0,Novel
42,Fear of Flying,Erica Jong,1973,37.0,Romantic novel
43,How the Steel Was Tempered (Как закалялась сталь),Nikolai Ostrovsky,1932,36.4,Socialist realist novel
44,War and Peace (Война и мир),Leo Tolstoy,1869,36.0,Historical novel
45,The Adventures of Pinocchio (Le avventure di P...,Carlo Collodi,1881,35.0,"Fantasy, children's fiction"
46,The Diary of Anne Frank (Het Achterhuis),Anne Frank,1947,35.0,"Historical non-fiction, autobiography, memoir,..."
47,Your Erroneous Zones,Wayne Dyer,1976,35.0,Self-help
48,The Thorn Birds,Colleen McCullough,1977,33.0,Romantic family saga
49,The Kite Runner,Khaled Hosseini,2003,31.5,"Bildungsroman, historical fiction"
50,Valley of the Dolls,Jacqueline Susann,1966,31.0,Novel
51,How to Win Friends and Influence People,Dale Carnegie,1936,37.0,Self-help
52,The Great Gatsby,F. Scott Fitzgerald,1925,30.0,"Novel, tragedy"
53,Gone with the Wind,Margaret Mitchell,1936,30.0,Historical fiction
54,Rebecca,Daphne du Maurier,1938,30.0,Gothic novel
55,The Revolt of Mamie Stover,William Bradford Huie,1951,30.0,Fiction
56,The Girl with the Dragon Tattoo (Män som hatar...,Stieg Larsson,2005,30.0,Fiction
57,The Lost Symbol,Dan Brown,2009,30.0,Fiction
58,The Hunger Games,Suzanne Collins,2008,29.0,"Young adult fiction, dystopia"
59,James and the Giant Peach,Roald Dahl,1961,28.0,Children's novel
60,Ben-Hur: A Tale of the Christ,Lew Wallace,1880,26.0,Novel
61,The Young Guard (Молодая гвардия),Alexander Alexandrovich Fadeyev,1945,26.0,Young adult historical novel
62,Who Moved My Cheese?,Spencer Johnson,1998,28[87] – 30[88],"Self-help, motivational, business fable, psych..."
63,A Brief History of Time,Stephen Hawking,1988,25.0,Popular science
64,Paul et Virginie,Jacques-Henri Bernardin de Saint-Pierre,1788,25.0,Novel
65,Lust for Life,Irving Stone,1934,25.0,Biographical novel
66,The Wind in the Willows,Kenneth Grahame,1908,25.0,Children's literature
67,The 7 Habits of Highly Effective People,Stephen R. Covey,1989,25.0,Self-help
68,Totto-Chan: The Little Girl at the Window (窓ぎわ...,Tetsuko Kuroyanagi,1981,25.0,Autobiographical novel
69,Virgin Soil Upturned (Поднятая целина),Mikhail Sholokhov,1935,24.0,Novel
70,The Celestine Prophecy,James Redfield,1993,23.0,New-age spiritual novel
71,The Fault in Our Stars,John Green,2012,23.0,Young adult romantic novel
72,The Girl on the Train,Paula Hawkins,2015,23.0,Thriller
73,The Shack,William P. Young,2007,22.5,Novel
74,Uncle Styopa (Дядя Стёпа),Sergey Mikhalkov,1936,21.0,"Children's Literature, picture book"
75,The Godfather,Mario Puzo,1969,21.0,Crime novel
76,Love Story,Erich Segal,1970,21.0,Romance novel
77,Catching Fire,Suzanne Collins,2009,21.0,"Young adult novel, adventure, dystopian, scien..."
78,Mockingjay,Suzanne Collins,2010,20.0,"Young Adult novel, adventure, war, science fic..."
79,Kitchen (キッチン),Banana Yoshimoto,1988,20.0,Japanese novel
80,Andromeda Nebula (Туманность Андромеды),Ivan Yefremov,1957,20.0,Science fiction novel
81,Gone Girl,Gillian Flynn,2012,20.0,Crime thriller novel
82,The Bermuda Triangle,Charles Berlitz,1974,20.0,
83,Things Fall Apart,Chinua Achebe,1958,20.0,Novel
84,Wolf Totem (狼图腾),Jiang Rong,2004,20.0,Semi-autobiographical novel
85,The Happy Hooker: My Own Story,Xaviera Hollander,1971,20.0,Memoir
86,Jaws,Peter Benchley,1974,20.0,Thriller
87,Love You Forever,Robert Munsch,1986,20.0,"Children's literature, picture book, fiction"
88,The Women's Room,Marilyn French,1977,20.0,Feminist novel
89,What to Expect When You're Expecting,Arlene Eisenberg and Heidi Murkoff,1984,20.0,Pregnancy guide
90,Adventures of Huckleberry Finn,Mark Twain,1885,20.0,"Picaresque novel, Bildungsroman, satire, Robin..."
91,"The Secret Diary of Adrian Mole, Aged 13¾",Sue Townsend,1982,20.0,Young adult novel
92,Pride and Prejudice,Jane Austen,1813,20.0,"Classic regency novel, romance"
93,Kon-Tiki: Across the Pacific in a Raft (Kon-Ti...,Thor Heyerdahl,1950,20.0,Travel literature
94,The Good Soldier Švejk (Osudy dobrého vojáka Š...,Jaroslav Hašek,1923,20.0,Unfinished satirical dark comedy novel
95,Where the Wild Things Are,Maurice Sendak,1963,20.0,Children's picture book
96,The Power of Positive Thinking,Norman Vincent Peale,1952,20.0,Self-help
97,The Secret,Rhonda Byrne,2006,20.0,Self-help
98,Dune,Frank Herbert,1965,20.0,Science fiction novel
99,Charlie and the Chocolate Factory,Roald Dahl,1964,20.0,Children's fantasy novel
100,The Naked Ape,Desmond Morris,1968,20.0,"Social Science, Anthropology, Psychology"
101,Kokoro (こゝろ),Natsume Sōseki,1914,20.0,Novel